In [1]:
import time
import cv2
import os
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
def dawOnMac():
    cv2.destroyAllWindows()
    for i in range (1,5):
        cv2.waitKey(1)

In [4]:
class BubbleCounter():

    def __init__(self):
        self.startTime = time.time()

        self.vidcap = cv2.VideoCapture('./KakaoTalk_20220131_002306209.mp4')
        self.success, self.image = self.vidcap.read()
        
        self.contourList = []


    def main(self):
        count = 0
        while self.success:
            cv2.imwrite("./sample00/%06d.jpg" % count, self.image)     # save frame as JPEG file
            self.success, self.image = self.vidcap.read()
            print('Read a new frame: ', self.success)
            count += 1



    def printInfo(self):
        print(type(self.image))
        print(self.image.shape)
        
    
    def cropCircle(self, img):
        mask = np.zeros((1080, 1920), np.uint8)
#         circle_img = cv2.circle(mask, (950, 500), radius=500, color=(255, 255, 255), thickness=-1)
        
        circle_img = cv2.circle(mask, (958, 498), radius=460, color=(255, 255, 255), thickness=-1)
    
        masked_data = cv2.bitwise_and(img, img, mask=circle_img)
        return masked_data
        
    def clbrScale(self, image, x1, y1, x2, y2):
        cv2.line(image, (x1, y1), (x2, y2), (0, 255, 0), thickness=2)
    
    
    def getSubtract(self):
        mat1 = np.array(self.imageList[-1])
        mat2 = np.array(self.imageList[-2])

        # to gray image
        gmat1 = cv2.cvtColor(mat1, cv2.COLOR_BGR2GRAY)
        gmat2 = cv2.cvtColor(mat2, cv2.COLOR_BGR2GRAY)

        BD = cv2.subtract(gmat1, gmat2)

        self.BDList.append(BD)
        self.BDList = self.BDList[-self.BDLen:]

        self.BDMaxList.append(BD.max())
        self.BDMaxList = self.BDMaxList[-self.BDLen:]

        self.BDSList.append(np.std(BD))
        self.BDSList = self.BDSList[-self.BDSListLen:]



    def imgLoad(self):
        img1 = cv2.imread('C:/Users/dlsxo/Desktop/bubble counter/sample00/000022.jpg')
        img1 = self.cropCircle(img1)
        img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
        

        img2 = cv2.imread('C:/Users/dlsxo/Desktop/bubble counter/sample00/000023.jpg')
        img2 = self.cropCircle(img2)
        img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

        BD = cv2.subtract(img1, img2)



        ret, img_binary = cv2.threshold(BD, 10, 255, 0)
        contours, hierarchy = cv2.findContours(img_binary, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

    
        for cnt in contours:
            cv2.drawContours(img2, [cnt], 0, (255, 0, 0), 2)  # blue


        while True:
            img2 = cv2.resize(img2, (960, 540)) #Resize image

            cv2.imshow('showImg', img2)

            if cv2.waitKey(1) & 0Xff == ord('q'):
                break


    def vPlay2(self):
        vidcap = cv2.VideoCapture('./KakaoTalk_20220131_002306209.mp4')
        success, image = vidcap.read()

        # video info
        print('Frame width:', int(vidcap.get(cv2.CAP_PROP_FRAME_WIDTH)))
        print('Frame height:', int(vidcap.get(cv2.CAP_PROP_FRAME_HEIGHT)))
        print('Frame count:', int(vidcap.get(cv2.CAP_PROP_FRAME_COUNT)))
        fps = vidcap.get(cv2.CAP_PROP_FPS)
        print('FPS:', fps)

        self.count = 0
        while success:
            print(self.count)
            
            img1 = self.cropCircle(image)

            success, image = vidcap.read()
            img2 = self.cropCircle(image)

            BD = cv2.subtract(img1, img2)
            
            ### scale estimate....
            
            y1 = 35
            y2 = 960
            # 925 -> ~34.4cm > 34 1 dot per ~0.37mm
            # 462.5+35
            # 498
            
            rr_scale = 460
            
            x1 = 495
            x2 = 1420
            # 925
            # 462.5+495
            # 958
            
            line_a = cv2.line(BD, (950, y1), (950, y2), (0, 255, 0), thickness=2)
            line_b = cv2.line(BD, (x1, 500), (x2, 500), (0, 255, 0), thickness=2)
            
            
            ### 

            ret, img_binary = cv2.threshold(BD, 50, 255, 0)
            
            img_binary = cv2.cvtColor(img_binary, cv2.COLOR_BGR2GRAY)

            contours, hierarchy = cv2.findContours(img_binary, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
            print(contours)
            print(len(contours))
            
            self.contourList.append(contours)
            
            
#             rstimg = cv2.drawContours(img2, contours, -1, (0, 255, 0), 2)  # blue
            rstimg = img2

            if contours:
                for ll in contours:
                    mdfcontourList = [[i[0][0] for i in ll.tolist()],\
                                      [i[0][1] for i in ll.tolist()]]

                    print(max(mdfcontourList[0]), min(mdfcontourList[0]))
                    print(max(mdfcontourList[1]), min(mdfcontourList[1]))

                    pt1, pt2 = (max(mdfcontourList[0]), max(mdfcontourList[1])),\
                    (min(mdfcontourList[0]), min(mdfcontourList[1]))

                    rstimg = cv2.rectangle(rstimg, pt1, pt2, (255,0,0), 2)

            else:
                print('pass!')
            

            rstimg = cv2.resize(rstimg, (960, 540)) #Resize image

#             cv2.imshow('showRaw', BD)
            cv2.imshow('showImg', rstimg)
            
            
            if cv2.waitKey(1) & 0Xff == ord('q'):
                break
                
            time.sleep(0.5)
            self.count += 1

#         cv2.destroyAllWindows()




    def vPlay3(self):        
        vidcap = cv2.VideoCapture('./KakaoTalk_20220131_002306209.mp4')
        success, image = vidcap.read()
        

        # video info
        print('Frame width:', int(vidcap.get(cv2.CAP_PROP_FRAME_WIDTH)))
        print('Frame height:', int(vidcap.get(cv2.CAP_PROP_FRAME_HEIGHT)))
        print('Frame count:', int(vidcap.get(cv2.CAP_PROP_FRAME_COUNT)))
        fps = vidcap.get(cv2.CAP_PROP_FPS)
        print('FPS:', fps)


        count = 0
        while success:


            img1 = self.cropCircle(image)
            # img1 = image
            # img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)


            success, image = vidcap.read()
            # print('Read a new frame: ', success)
            print(count)

            img2 = self.cropCircle(image) # cut img to circle
            # img2 = image
            # img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

            
            self.BD = cv2.subtract(img1, img2)

            self.BD = cv2.resize(self.BD, (960, 540)) #Resize image
            
#             self.histBD = np.histogram(self.BD, bins=5)
            
#             cv2.putText(img=self.BD, text=str(count), org=(50, 500), \
#                         fontFace=cv2.FONT_HERSHEY_TRIPLEX, fontScale=1, color=(0, 0, 255),thickness=1)
            
            fig = plt.figure(figsize=(16,8))
#             print(self.BD.shape)
#             print(type(self.BD))
            histBD = np.reshape(bc.BD, -1)

            histBD = np.delete(histBD, np.where(histBD == 0))        
#             print(np.percentile(histBD, 95))
            histBD = np.delete(histBD, np.where(histBD < np.percentile(histBD, 95)))



#             plt.hist(histBD, bins=np.linspace(0, 255, num=50))

            print(np.unique(histBD))            
            print(sum(histBD)/len(histBD))
            

            plt.imshow(255 - self.BD)
            plt.show()

#             cv2.imshow('showImg', self.BD)




            if cv2.waitKey(1) & 0Xff == ord('q'):
                break

            time.sleep(0.5)
            count += 1


In [5]:
# if __name__=='__main__':

bc = BubbleCounter()

# bc.main()

# bc.printInfo()
# bc.cropCircle()

# bc.imgLoad()

# bc.vPlay()
bc.vPlay2()
# bc.vPlay3()
# cv2.destroyAllWindows()
dawOnMac()




Frame width: 1920
Frame height: 1080
Frame count: 2219
FPS: 29.99053926206244
0
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
1
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499

14
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
15
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]],

28
(array([[[1329,  384]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32))
2
1329 1329
384 384
1421 494
961 34
29
(array([[[1004,  241]],

       [[1003,  242]],

       [[1002,  242]],

       [[1002,  243]],

       [[1004,  243]],

       [[1006,  245]],

       [[1007,  245]],

       [[1007,  244]],

       [[1008,  243]],

       [[1007,  242]],

       [[1005,  242]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

  

40
(array([[[983, 849]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32))
2
983 983
849 849
1421 494
961 34
41
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]

54
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
55
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]],

69
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
70
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]],

85
(array([[[899, 684]],

       [[896, 687]],

       [[896, 690]],

       [[897, 691]],

       [[898, 691]],

       [[899, 690]],

       [[900, 690]],

       [[901, 689]],

       [[898, 689]],

       [[897, 688]],

       [[897, 687]],

       [[899, 685]],

       [[900, 685]],

       [[901, 686]],

       [[900, 687]],

       [[902, 687]],

       [[901, 686]],

       [[901, 684]]], dtype=int32), array([[[901, 682]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32))
3
902 896
691 684
901 901
682 682
1421 494
961 34
86
(ar

100
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
101
(array([[[1059,  836]],

       [[1060,  836]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       

114
(array([[[995, 851]],

       [[995, 852]]], dtype=int32), array([[[1306,  524]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32))
3
995 995
852 851
1306 1306
524 524
1421 494
961 34
115
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[142

129
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
130
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]

142
(array([[[961, 153]],

       [[961, 154]],

       [[962, 155]],

       [[962, 153]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32))
2
962 961
155 153
1421 494
961 34
143
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],



158
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
159
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]

173
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
174
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]

187
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
188
(array([[[1124,  811]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       

199
(array([[[955, 767]],

       [[956, 768]],

       [[956, 767]]], dtype=int32), array([[[1148,  101]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  768]],

       [[ 952,  767]],

       [[ 951,  766]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32))
3
956 955
768 767
1148 1148
101 101
1421 494
961 34
200
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,

212
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
213
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]

227
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
228
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]

241
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
242
(array([[[1044,  732]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       

254
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
255
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]

269
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
270
(array([[[865, 276]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[

284
(array([[[1382,  537]],

       [[1383,  537]]], dtype=int32), array([[[1378,  536]]], dtype=int32), array([[[1403,  527]],

       [[1404,  528]],

       [[1406,  528]],

       [[1407,  527]]], dtype=int32), array([[[1392,  518]],

       [[1391,  519]],

       [[1390,  519]],

       [[1392,  519]],

       [[1393,  518]]], dtype=int32), array([[[1362,  512]],

       [[1364,  512]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32))
6
1383 1382
537 537
1378 1378
536 536
1407 1403
528 527
1393 1390
519 518
1364 1362
512 512
142

297
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
298
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]

311
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
312
(array([[[663, 531]],

       [[663, 532]]], dtype=int32), array([[[664, 527]],

       [[664, 529]],

       [[665, 528]],

       [[665, 527]]], dtype=int32), array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

     

325
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
326
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]

341
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
342
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]

357
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]], dtype=int32),)
1
1421 494
961 34
358
(array([[[ 950,   34]],

       [[ 949,   35]],

       [[ 949,  498]],

       [[ 948,  499]],

       [[ 495,  499]],

       [[ 494,  500]],

       [[ 495,  501]],

       [[ 948,  501]],

       [[ 949,  502]],

       [[ 949,  960]],

       [[ 950,  961]],

       [[ 951,  960]],

       [[ 951,  502]],

       [[ 952,  501]],

       [[1420,  501]],

       [[1421,  500]],

       [[1420,  499]],

       [[ 952,  499]],

       [[ 951,  498]],

       [[ 951,   35]]

In [6]:
dawOnMac()

In [7]:
# for ii in range(bc.count):
#     try:
#         mdfcontourList = [[i[0][0] for i in bc.contourList[ii][0].tolist()],\
#                           [i[0][1] for i in bc.contourList[ii][0].tolist()]]
        
#         print(max(mdfcontourList[0]), min(mdfcontourList[0]))
#         print(max(mdfcontourList[1]), min(mdfcontourList[1]))
#     except:
#         print('pass!')
#         pass

In [8]:
bc.BD.shape

AttributeError: 'BubbleCounter' object has no attribute 'BD'

In [ ]:
np.reshape(bc.BD, -1).shape

In [ ]:
np.unique(np.reshape(bc.BD, -1))

In [ ]:
np.percentile(np.linspace(0, 255, 100), 99)